// import 'rxjs/add/operator/retrywhen';
// import 'rxjs/add/operator/retry';
// import 'rxjs/add/operator/delay';
// import 'rxjs/add/operator/filter';
// import 'rxjs/add/operator/concatMap';
// import 'rxjs/add/operator/combineLatest';
// import 'rxjs/add/operator/debounceTime';
// import 'rxjs/add/operator/do';
// import 'rxjs/add/operator/shareReplay';
// import 'rxjs/add/observable/of';
// import 'rxjs/add/observable/combineLatest';
// import 'rxjs/add/operator/mergeMap';
// import 'rxjs/add/operator/pluck';
// import 'rxjs/add/operator/distinctUntilChanged';
// import 'rxjs/add/operator/catch';
import { switchMap } from 'rxjs/operators';
import { map } from 'rxjs/operators';
import { of } from 'rxjs/observable/of';

export const rxjs_imports = [switchMap, map, of];
